# Generated by Django 4.0.3 on 2022-05-07 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
