# Generated by Django 4.0.3 on 2022-05-07 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
    ]
