# Generated by Django 4.0.3 on 2022-04-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OSes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='OS', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryTime', models.DurationField()),
                ('deliveryCharge', models.BooleanField()),
                ('price', models.IntegerField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brands')),
                ('displayType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.displaytypes')),
                ('operatingSystem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.oses')),
                ('productType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.producttypes')),
            ],
        ),
    ]
