# Generated by Django 4.0.3 on 2022-04-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='DisplayTypes',
            new_name='DisplayType',
        ),
        migrations.RenameModel(
            old_name='OSes',
            new_name='OS',
        ),
        migrations.RenameModel(
            old_name='ProductTypes',
            new_name='ProductType',
        ),
    ]
